-- =====================================================================
-- Wreckfest Race Log — full catalogue seed
-- Generated from https://wreckfest.fandom.com/wiki/Tracks
--                  https://wreckfest.fandom.com/wiki/Vehicles
-- Idempotent: safe to re-run. Existing rows are kept.
-- =====================================================================

begin;

-- Tracks ----------------------------------------------------------------
insert into public.tracks (name, slug) values ('Big Valley Speedway', 'big-valley-speedway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Bleak City', 'bleak-city') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Bloomfield Speedway', 'bloomfield-speedway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Bonebreaker Valley', 'bonebreaker-valley') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Boulder Bank Circuit', 'boulder-bank-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Clayridge Circuit', 'clayridge-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Crash Canyon', 'crash-canyon') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Deathloop', 'deathloop') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Devil''s Canyon', 'devil-s-canyon') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Dirt Devil Stadium', 'dirt-devil-stadium') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Drytown Desert Circuit', 'drytown-desert-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Eagles Peak Motorpark', 'eagles-peak-motorpark') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Espedalen Raceway', 'espedalen-raceway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('FinnCross Circuit', 'finncross-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Fire Rock Raceway', 'fire-rock-raceway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Firwood Motocenter', 'firwood-motocenter') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Hellride', 'hellride') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Hillstreet Circuit', 'hillstreet-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Hilltop Stadium', 'hilltop-stadium') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Kingston Raceway', 'kingston-raceway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Maasten Motocenter', 'maasten-motocenter') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Madman Stadium', 'madman-stadium') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Midwest Motocenter', 'midwest-motocenter') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Motorcity Circuit', 'motorcity-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Mudford Motorpark', 'mudford-motorpark') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Northfolk Ring', 'northfolk-ring') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Northland Raceway', 'northland-raceway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Pinehills Raceway', 'pinehills-raceway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Rally Trophy', 'rally-trophy') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Rattlesnake Racepark', 'rattlesnake-racepark') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Rockfield Roughspot', 'rockfield-roughspot') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Rosenheim Raceway', 'rosenheim-raceway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Sandstone Raceway', 'sandstone-raceway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Savolax Sandpit', 'savolax-sandpit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Torsdalen Circuit', 'torsdalen-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Tribend Speedway', 'tribend-speedway') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Vale Falls Circuit', 'vale-falls-circuit') on conflict (slug) do update set name = excluded.name;
insert into public.tracks (name, slug) values ('Wrecknado', 'wrecknado') on conflict (slug) do update set name = excluded.name;

-- Track variations ------------------------------------------------------
insert into public.track_variations (track_id, name, slug) select id, 'Figure 8', 'figure-8' from public.tracks where slug = 'big-valley-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Inner Oval', 'inner-oval' from public.tracks where slug = 'big-valley-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Outer Oval', 'outer-oval' from public.tracks where slug = 'big-valley-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Outer Oval Loop', 'outer-oval-loop' from public.tracks where slug = 'big-valley-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Race Track', 'race-track' from public.tracks where slug = 'bleak-city' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Race Track Reverse', 'race-track-reverse' from public.tracks where slug = 'bleak-city' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Dirt Oval', 'dirt-oval' from public.tracks where slug = 'bloomfield-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Figure 8', 'figure-8' from public.tracks where slug = 'bloomfield-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'bonebreaker-valley' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Route', 'main-route' from public.tracks where slug = 'boulder-bank-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Route Reverse', 'main-route-reverse' from public.tracks where slug = 'boulder-bank-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Route', 'short-route' from public.tracks where slug = 'boulder-bank-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Route Reverse', 'short-route-reverse' from public.tracks where slug = 'boulder-bank-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'clayridge-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'clayridge-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'crash-canyon' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'deathloop' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Race Track', 'race-track' from public.tracks where slug = 'devil-s-canyon' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Dirt Speedway', 'dirt-speedway' from public.tracks where slug = 'dirt-devil-stadium' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'drytown-desert-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'drytown-desert-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Racing Track', 'racing-track' from public.tracks where slug = 'eagles-peak-motorpark' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Racing Track Reverse', 'racing-track-reverse' from public.tracks where slug = 'eagles-peak-motorpark' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'espedalen-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'espedalen-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit', 'short-circuit' from public.tracks where slug = 'espedalen-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit Reverse', 'short-circuit-reverse' from public.tracks where slug = 'espedalen-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'finncross-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'finncross-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'fire-rock-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'fire-rock-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit', 'short-circuit' from public.tracks where slug = 'fire-rock-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit Reverse', 'short-circuit-reverse' from public.tracks where slug = 'fire-rock-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'firwood-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'firwood-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Rally Circuit', 'rally-circuit' from public.tracks where slug = 'firwood-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Rally Circuit Reverse', 'rally-circuit-reverse' from public.tracks where slug = 'firwood-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit', 'short-circuit' from public.tracks where slug = 'firwood-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit Reverse', 'short-circuit-reverse' from public.tracks where slug = 'firwood-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'hellride' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Race Track', 'race-track' from public.tracks where slug = 'hillstreet-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Race Track Reverse', 'race-track-reverse' from public.tracks where slug = 'hillstreet-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Figure 8', 'figure-8' from public.tracks where slug = 'hilltop-stadium' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Oval', 'oval' from public.tracks where slug = 'hilltop-stadium' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Asphalt Oval', 'asphalt-oval' from public.tracks where slug = 'kingston-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Asphalt Oval Reverse', 'asphalt-oval-reverse' from public.tracks where slug = 'kingston-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Figure 8', 'figure-8' from public.tracks where slug = 'kingston-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'maasten-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'maasten-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Figure 8', 'figure-8' from public.tracks where slug = 'madman-stadium' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'midwest-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'midwest-motocenter' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'motorcity-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'motorcity-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Trophy Circuit', 'trophy-circuit' from public.tracks where slug = 'motorcity-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Mud Oval', 'mud-oval' from public.tracks where slug = 'mudford-motorpark' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'northfolk-ring' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Open Circuit', 'open-circuit' from public.tracks where slug = 'northfolk-ring' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'northfolk-ring' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Outer Route', 'outer-route' from public.tracks where slug = 'northland-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Outer Route Reverse', 'outer-route-reverse' from public.tracks where slug = 'northland-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Inner Route', 'inner-route' from public.tracks where slug = 'northland-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Inner Route Reverse', 'inner-route-reverse' from public.tracks where slug = 'northland-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Free Route', 'free-route' from public.tracks where slug = 'northland-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'pinehills-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'pinehills-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Rally Circuit', 'rally-circuit' from public.tracks where slug = 'pinehills-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Rally Circuit Reverse', 'rally-circuit-reverse' from public.tracks where slug = 'pinehills-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit', 'short-circuit' from public.tracks where slug = 'pinehills-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit Reverse', 'short-circuit-reverse' from public.tracks where slug = 'pinehills-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Special Stage', 'special-stage' from public.tracks where slug = 'rally-trophy' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'rattlesnake-racepark' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'rattlesnake-racepark' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Dirt Oval', 'dirt-oval' from public.tracks where slug = 'rockfield-roughspot' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'rosenheim-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'rosenheim-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Route', 'main-route' from public.tracks where slug = 'sandstone-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Route Reverse', 'main-route-reverse' from public.tracks where slug = 'sandstone-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Route', 'short-route' from public.tracks where slug = 'sandstone-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Route Reverse', 'short-route-reverse' from public.tracks where slug = 'sandstone-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Alt Route', 'alt-route' from public.tracks where slug = 'sandstone-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Alt Route Reverse', 'alt-route-reverse' from public.tracks where slug = 'sandstone-raceway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Route', 'main-route' from public.tracks where slug = 'savolax-sandpit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Route Reverse', 'main-route-reverse' from public.tracks where slug = 'savolax-sandpit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Route', 'short-route' from public.tracks where slug = 'savolax-sandpit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Route Reverse', 'short-route-reverse' from public.tracks where slug = 'savolax-sandpit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'torsdalen-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'torsdalen-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit', 'short-circuit' from public.tracks where slug = 'torsdalen-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit Reverse', 'short-circuit-reverse' from public.tracks where slug = 'torsdalen-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'tribend-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Reverse Circuit', 'reverse-circuit' from public.tracks where slug = 'tribend-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Wild Circuit', 'wild-circuit' from public.tracks where slug = 'tribend-speedway' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'vale-falls-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit Reverse', 'main-circuit-reverse' from public.tracks where slug = 'vale-falls-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit', 'short-circuit' from public.tracks where slug = 'vale-falls-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Short Circuit Reverse', 'short-circuit-reverse' from public.tracks where slug = 'vale-falls-circuit' on conflict (track_id, slug) do update set name = excluded.name;
insert into public.track_variations (track_id, name, slug) select id, 'Main Circuit', 'main-circuit' from public.tracks where slug = 'wrecknado' on conflict (track_id, slug) do update set name = excluded.name;

-- Vehicles --------------------------------------------------------------
insert into public.vehicles (name) values ('Rocket') on conflict (name) do nothing;
insert into public.vehicles (name) values ('KillerBee') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Firefly') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Gremlin') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Tristar') on conflict (name) do nothing;
insert into public.vehicles (name) values ('MudDigger') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Rammer') on conflict (name) do nothing;
insert into public.vehicles (name) values ('El Matador') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Nexus RX') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Dominator') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Boomer') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hammerhead') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hotshot') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Starbeast') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Warwagon') on conflict (name) do nothing;
insert into public.vehicles (name) values ('RoadSlayer') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Gatecrasher') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Roadcutter') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Panther RS') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Sunrise Super') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Bulldog') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Speedemon') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Speedbird') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Lawn Mower') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Sofa Car') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Supervan') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Rammer RS') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Harvester') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Limo') on conflict (name) do nothing;
insert into public.vehicles (name) values ('School Bus') on conflict (name) do nothing;
insert into public.vehicles (name) values ('KillerBee S') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Motorhome') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Double Decker') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Boomer RS') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Big Rig') on conflict (name) do nothing;
insert into public.vehicles (name) values ('RoadSlayer GT') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Venom') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Bandit') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Bandit Ripper V8') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Wingman') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Buggy') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Bumper Car') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Outlaw') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hornet') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Honey Pot') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Bugzilla') on conflict (name) do nothing;
insert into public.vehicles (name) values ('WarDigger') on conflict (name) do nothing;
insert into public.vehicles (name) values ('DragSlayer') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Pocket Rocket') on conflict (name) do nothing;
insert into public.vehicles (name) values ('KillerPig') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Raiden RS') on conflict (name) do nothing;
insert into public.vehicles (name) values ('RebelRat') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Vandal') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Grand Duke') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Wildking') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Little Thrasher') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Sweeper') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hearse') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Stock Car') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Bullet') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Razor') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Cardinal') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Raven') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Stellar') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Speedie') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Gorbie') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Blade') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Step Van') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Trooper') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Trophy Runner') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Sandstorm') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Bandit Ripper R2') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Doom Rig') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Super Venom') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hunter Panther') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hellvester') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Rocket RX') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Battle Bus') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Starbeast SS') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hammerhead RS') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Speedbird GT') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Eagle R') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Hotbomb') on conflict (name) do nothing;
insert into public.vehicles (name) values ('Harvesteri') on conflict (name) do nothing;

commit;
